{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let page_limit=30
     can_edit=false()}
{*     list_count=fetch('content','draft_count')} *}
<form action={concat("content/bookmark/")|ezurl} method='post' >


{let bookmark_list=fetch('content','bookmarks',array())}

{section show=$bookmark_list}

<p>
    {"These are the objects you have bookmarked. Click on an object to view it or if you have permission you can edit the object by clicking the edit button.
      If you want to add more objects to this list click the %emphasize_startAdd bookmarks%emphasize_stop button.

      Removing objects will only remove them from this list."
      |i18n("design/standard/content/view",,
            hash( '%emphasize_start', '<i>',
                  '%emphasize_stop', '</i>' ) )
      |nl2br}
</p>

{section loop=$bookmark_list}
  {section show=$:item.node.object.can_edit}
    {set can_edit=true()}
  {/section}
{/section}

<table cellspacing="0" cellpadding="0" border="0" width="290" >
<tr>
    <th width="1">
    </th>
    <th width="69%">
        <strong>{"Name"|i18n("design/standard/content/view")}</strong>
    </th>
    {section show=$can_edit}
        <th width="1">
            <strong>{'Edit'|i18n('design/standard/content/view')}</strong>
        </th>
    {/section}
</tr>

{section name=Bookmark loop=$bookmark_list sequence=array(bgdark,bglight)}
<tr>
    <td align="left">
        <input type="checkbox" name="DeleteIDArray[]" value="{$:item.id}" />
    </td>

    <td>
        <a href={concat("/content/view/full/",$:item.node_id,"/")|ezurl}>{$:item.node.object.content_class.identifier|class_icon( small, $:item.node.object.content_class.name )}&nbsp;{$:item.node.name|wash}</a>
    </td>

    {section show=$can_edit}
        <td width="1">
            {section show=$:item.node.object.can_edit}
                <a href={concat("content/edit/",$:item.node.contentobject_id)|ezurl}><img src={"edit.gif"|ezimage} alt="{'Edit'|i18n('design/standard/content/view')}" /></a>
            {/section}
        </td>
    {/section}
</tr>
{/section}

<tr>
    <td align="left">
        <input type="image" name="RemoveButton" value="{'Remove'|i18n('design/standard/content/view')}" src={"trash.png"|ezimage} alt="{'Remove'|i18n('design/standard/content/view')}" />
    </td>
    <td colspan="3">
    </td>
</tr>
</table>

{section-else}

<div class="feedback">
    <h2>{"You have no bookmarks"|i18n("design/standard/content/view")}</h2>
</div>

{/section}
<br/>
<div class="buttonblock">
    <input class="defaultbutton" type="submit" name="AddButton" value="{'Add bookmarks'|i18n('design/standard/content/view')}" />
</div>


</form>

{/let}

{/let}

